import { useMemo, useState } from 'react';
import { FlaskConical } from 'lucide-react';
import { Card } from '../components/ui';
import { ThresholdPlot } from '../components/charts/ThresholdPlot';
import { thresholdCurves, thresholdSemantics } from '../services/qecGrid';
import type { QecCode, QecNoiseModel } from '../services/contracts';

const CODES: { id: QecCode; label: string }[] = [
  { id: 'repetition', label: 'Repetition' },
  { id: 'rotated_surface', label: 'Rotated surface' },
];
const NOISE: { id: QecNoiseModel; label: string }[] = [
  { id: 'code_capacity', label: 'Code-capacity' },
  { id: 'phenomenological', label: 'Phenomenological' },
  { id: 'circuit_level', label: 'Circuit-level' },
];
const DISTANCES = [3, 5, 7];

function Pills<T extends string>({ options, value, onChange, label }: { options: { id: T; label: string }[]; value: T; onChange: (v: T) => void; label: string }) {
  return (
    <div>
      <div className="mb-1 text-caption text-text-muted">{label}</div>
      <div className="flex flex-wrap gap-1.5" role="group" aria-label={label}>
        {options.map((o) => (
          <button key={o.id} onClick={() => onChange(o.id)} aria-pressed={o.id === value}
            className={'rounded-chip border px-2.5 py-1 text-body-s transition-colors ' +
              (o.id === value ? 'border-border-control bg-row-selected text-text-primary' : 'border-border-hairline text-text-secondary hover:bg-row-hover')}>
            {o.label}
          </button>
        ))}
      </div>
    </div>
  );
}

// QEC Lab: reads the REAL committed threshold grid (demo-data/qec) generated by Stim + PyMatching.
export function QecLab() {
  const [code, setCode] = useState<QecCode>('rotated_surface');
  const [noise, setNoise] = useState<QecNoiseModel>('circuit_level');

  const curves = useMemo(() => thresholdCurves({ code, noise_model: noise, distances: DISTANCES }), [code, noise]);
  const sem = thresholdSemantics(code);
  const totalRows = curves.reduce((n, c) => n + c.rows.length, 0);

  return (
    <div className="flex flex-col gap-5">
      <header className="flex items-start justify-between gap-4">
        <div>
          <p className="text-eyebrow uppercase text-series-logical">QEC Lab</p>
          <h2 className="text-display-m">Logical error vs physical error</h2>
          <p className="mt-1 max-w-2xl text-body-s text-text-muted">
            Curves are read from the committed grid produced by a real Stim + PyMatching (MWPM)
            simulation. Where the distance curves cross is the threshold region — below it, adding
            distance suppresses logical error; above it, it makes things worse.
          </p>
        </div>
        <span className="shrink-0 rounded-chip border border-border-hairline bg-state-uncertain-bg px-2 py-1 text-caption text-state-uncertain">
          Simulated
        </span>
      </header>

      <div className="grid gap-4 lg:grid-cols-[260px_1fr]">
        <Card className="flex flex-col gap-4 p-4">
          <Pills options={CODES} value={code} onChange={setCode} label="Code family" />
          <Pills options={NOISE} value={noise} onChange={setNoise} label="Noise model" />
          <div className="rounded-control border border-border-hairline bg-bg-base p-3">
            <div className="flex items-center gap-1.5 text-caption text-text-muted"><FlaskConical size={12} aria-hidden /> threshold behaviour</div>
            <p className="mt-1 text-body-s text-text-primary">{sem.label}</p>
          </div>
          <div className="text-caption text-text-muted">
            distances {DISTANCES.join(' / ')} · {totalRows} data points · decoder MWPM (PyMatching)
          </div>
        </Card>

        <div className="flex flex-col gap-3">
          <ThresholdPlot
            curves={curves}
            summary={
              'Logical error rate versus physical error rate for code ' + code + ' under ' + noise +
              ' noise, at distances ' + DISTANCES.join(', ') + '. Lower curves at small physical error indicate error suppression.'
            }
          />
          <div className="grid gap-3 sm:grid-cols-3">
            {curves.map((c) => {
              const best = c.rows[0];
              return (
                <Card key={c.distance} className="p-3">
                  <div className="text-eyebrow uppercase text-text-secondary">distance {c.distance}</div>
                  <div className="mt-1 metric text-metric-m text-text-primary">{c.physical_qubits}<span className="ml-1 text-body-s text-text-muted">qubits</span></div>
                  {best && (
                    <div className="mt-1 text-caption text-text-muted">
                      best logical err {best.logical_error_rate === 0 ? '< 1 / shots' : best.logical_error_rate.toExponential(1)}
                    </div>
                  )}
                </Card>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}
