import { useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { FlaskConical, Target } from 'lucide-react';
import { fmtSci } from '../components/charts/scale';
import { Card } from '../components/ui';
import { ThresholdPlot } from '../components/charts/ThresholdPlot';
import { lookupPoint, thresholdCurves, thresholdSemantics } from '../services/qecGrid';
import type { QecCode, QecNoiseModel } from '../services/contracts';
import { logicalBudget, verdictFor, VERDICT_LABEL } from '../services/qecBudget';

const CODES: { id: QecCode; label: string }[] = [
  { id: 'repetition', label: 'Repetition' },
  { id: 'rotated_surface', label: 'Rotated surface' },
];
const NOISE: { id: QecNoiseModel; label: string }[] = [
  { id: 'code_capacity', label: 'Code-capacity' },
  { id: 'phenomenological', label: 'Phenomenological' },
  { id: 'circuit_level', label: 'Circuit-level' },
];
const DISTANCES = [3, 5, 7];

function Pills<T extends string>({ options, value, onChange, label }: { options: { id: T; label: string }[]; value: T; onChange: (v: T) => void; label: string }) {
  return (
    <div>
      <div className="mb-1 text-caption text-text-muted">{label}</div>
      <div className="flex flex-wrap gap-1.5" role="group" aria-label={label}>
        {options.map((o) => (
          <button key={o.id} onClick={() => onChange(o.id)} aria-pressed={o.id === value}
            className={'rounded-chip border px-2.5 py-1 text-body-s transition-colors ' +
              (o.id === value ? 'border-border-control bg-row-selected text-text-primary' : 'border-border-hairline text-text-secondary hover:bg-row-hover')}>
            {o.label}
          </button>
        ))}
      </div>
    </div>
  );
}

// QEC Lab: reads the REAL committed threshold grid (demo-data/qec) generated by Stim + PyMatching.
export function QecLab() {
  const [code, setCode] = useState<QecCode>('rotated_surface');
  const [noise, setNoise] = useState<QecNoiseModel>('circuit_level');

  // Context handed over from a New Analysis that hit the QEM ceiling, so the user does not have to
  // re-state their target here. Absent when the lab is opened directly.
  const [params] = useSearchParams();
  const carriedTarget = Number(params.get('target')) || null;
  const carriedP = Number(params.get('p')) || null;
  // Circuit shape travels with the target: without it the observable error cannot be converted
  // into a per-round logical budget at all (see services/qecBudget).
  const carriedQubits = Number(params.get('nq')) || null;
  const carriedDepth = Number(params.get('depth')) || null;

  const curves = useMemo(() => thresholdCurves({ code, noise_model: noise, distances: DISTANCES }), [code, noise]);
  const sem = thresholdSemantics(code);

  /**
   * Convert the carried QEM target into a per-round logical budget before comparing anything.
   * The two quantities are not interchangeable, which is what the old code assumed.
   */
  const budget = useMemo(() => {
    if (!carriedTarget || !carriedQubits || !carriedDepth) return null;
    return logicalBudget({
      targetObservableError: carriedTarget,
      logicalQubits: carriedQubits,
      logicalDepth: carriedDepth,
      // d rounds per logical layer for a distance-d code; the largest distance is the planning case.
      roundsPerLayer: Math.max(...DISTANCES),
    });
  }, [carriedTarget, carriedQubits, carriedDepth]);

  /**
   * Per distance: the grid point AT the carried physical error, or an explicit off-grid report.
   * `lookupPoint` exists precisely so nothing silently substitutes a neighbouring simulation, and
   * this page used to do exactly that behind the user's back.
   */
  const plan = useMemo(() => {
    if (!budget || !carriedP) return null;
    return curves.map((c) => {
      const hit = lookupPoint(code, noise, c.distance, carriedP);
      const row = hit.row;
      const rate = row?.logical_error_rate_per_round ?? null;
      return {
        distance: c.distance,
        qubits: c.physical_qubits,
        gridStatus: hit.grid_status,
        nearestP: hit.nearest_p,
        p: row?.p ?? null,
        rate,
        upper: row?.lerpr_ci_high ?? null,
        verdict: verdictFor(rate, row?.lerpr_ci_high ?? null, budget.perRoundBudget),
        zeroObserved: row?.logical_errors === 0,
      };
    });
  }, [curves, budget, carriedP, code, noise]);

  const offGrid = plan?.some((d) => d.gridStatus === 'off_grid') ?? false;
  // Only a verdict backed by the confidence bound may be recommended.
  const recommended = plan?.find((d) => d.verdict === 'meets') ?? null;
  const totalRows = curves.reduce((n, c) => n + c.rows.length, 0);

  return (
    <div className="flex flex-col gap-5">
      <header className="flex items-start justify-between gap-4">
        <div>
          <p className="text-eyebrow uppercase text-series-logical">QEC Lab</p>
          <h2 className="font-display text-display-m font-normal">Logical error vs physical error</h2>
          <p className="mt-1 max-w-2xl text-body-s text-text-muted">
            Curves are read from the committed grid produced by a real Stim + PyMatching (MWPM)
            simulation. Where the distance curves cross is the threshold region — below it, adding
            distance suppresses logical error; above it, it makes things worse.
          </p>
        </div>
        <span className="shrink-0 rounded-chip border border-border-hairline bg-state-uncertain-bg px-2 py-1 text-caption text-state-uncertain">
          Simulated
        </span>
      </header>

      <div className="grid gap-4 lg:grid-cols-[260px_1fr]">
        <Card className="flex flex-col gap-4 p-4">
          <Pills options={CODES} value={code} onChange={setCode} label="Code family" />
          <Pills options={NOISE} value={noise} onChange={setNoise} label="Noise model" />
          <div className="rounded-control border border-border-hairline bg-bg-base p-3">
            <div className="flex items-center gap-1.5 text-caption text-text-muted"><FlaskConical size={12} aria-hidden /> threshold behaviour</div>
            <p className="mt-1 text-body-s text-text-primary">{sem.label}</p>
          </div>
          <div className="text-caption text-text-muted">
            distances {DISTANCES.join(' / ')} · {totalRows} data points · decoder MWPM (PyMatching)
          </div>
        </Card>

        <div className="flex flex-col gap-3">
          {plan && budget && carriedTarget && carriedP && (
            <Card lit className="p-4">
              <div className="mb-2 flex items-center gap-2">
                <Target size={15} className="text-series-logical" aria-hidden />
                <h3 className="text-eyebrow uppercase text-text-secondary">QEC planning — carried from analysis</h3>
              </div>
              <p className="text-body-s text-text-secondary">
                The analysis target is an absolute error on ⟨O⟩, not a logical error rate. It is
                converted into a per-round budget before anything is compared:
              </p>
              <ol className="mt-2 rounded-control border border-border-hairline bg-bg-base p-2.5 text-caption text-text-secondary">
                {budget.steps.map((step) => (
                  <li key={step} className="metric py-0.5">
                    {step}
                  </li>
                ))}
              </ol>
              <p className="mt-2 text-body-s text-text-secondary">
                Required{' '}
                <span className="metric text-text-primary">{fmtSci(budget.perRoundBudget)}</span> per
                round at physical error{' '}
                <span className="metric text-text-primary">{fmtSci(carriedP)}</span>.
              </p>

              {offGrid && (
                <p className="mt-2 rounded-control border border-state-uncertain/40 bg-state-uncertain-bg p-2.5 text-caption text-text-secondary">
                  <span className="metric text-state-uncertain">off grid</span> — the carried
                  physical error rate was not simulated. Nothing is substituted for it; each card
                  below names the nearest simulated point instead of quietly answering with it.
                </p>
              )}
              <div className="mt-3 grid gap-2 sm:grid-cols-3">
                {plan.map((d) => (
                  <div
                    key={d.distance}
                    className={
                      'rounded-control border p-2.5 ' +
                      (d.distance === recommended?.distance
                        ? 'border-series-logical bg-state-uncertain-bg'
                        : 'border-border-hairline')
                    }
                  >
                    <div className="flex items-baseline justify-between gap-2">
                      <span className="text-body-s text-text-primary">d = {d.distance}</span>
                      <span
                        className={
                          'text-caption ' +
                          (d.verdict === 'meets'
                            ? 'text-state-healthy'
                            : d.verdict === 'likely'
                              ? 'text-state-uncertain'
                              : 'text-state-warning')
                        }
                      >
                        {d.gridStatus === 'off_grid' ? 'not simulated' : VERDICT_LABEL[d.verdict]}
                      </span>
                    </div>
                    <div className="metric mt-1 text-metric-s text-text-primary">{d.qubits} qubits</div>
                    {d.gridStatus === 'off_grid' ? (
                      <div className="text-caption text-text-muted">
                        nearest simulated p ={' '}
                        <span className="metric">{d.nearestP == null ? '—' : fmtSci(d.nearestP)}</span>
                      </div>
                    ) : (
                      <div className="text-caption text-text-muted">
                        {d.rate == null
                          ? 'no per-round rate'
                          : (d.zeroObserved ? '0 failures · ' : '') + d.rate.toExponential(1)}{' '}
                        / round
                        {d.upper != null && (
                          <>
                            {' '}
                            · 95% upper <span className="metric">{d.upper.toExponential(1)}</span>
                          </>
                        )}
                      </div>
                    )}
                  </div>
                ))}
              </div>
              <p className="mt-3 rounded-control border border-border-hairline bg-bg-base p-2.5 text-body-s">
                {recommended ? (
                  <>
                    <span className="text-text-secondary">Planning point: </span>
                    <span className="text-series-logical">
                      {CODES.find((c) => c.id === code)?.label ?? code}, distance{' '}
                      {recommended.distance} — {recommended.qubits} structural physical qubits, MWPM
                      decoder.
                    </span>
                  </>
                ) : (
                  <span className="text-state-warning">
                    No simulated distance clears the per-round budget with 95% confidence at this
                    physical error. A lower physical error rate, a larger distance than d=
                    {Math.max(...DISTANCES)}, or more simulation statistics would be required.
                  </span>
                )}
              </p>
              <p className="mt-1.5 text-caption text-text-muted">
                Planning estimate from simulated grid points — structural qubit counts only, not a
                fault-tolerance resource calculation.
              </p>
            </Card>
          )}

          <ThresholdPlot
            curves={curves}
            summary={
              'Logical error rate versus physical error rate for code ' + code + ' under ' + noise +
              ' noise, at distances ' + DISTANCES.join(', ') + '. Lower curves at small physical error indicate error suppression.'
            }
          />
          <div className="grid gap-3 sm:grid-cols-3">
            {curves.map((c) => {
              const best = c.rows[0];
              return (
                <Card key={c.distance} className="p-3">
                  <div className="text-eyebrow uppercase text-text-secondary">distance {c.distance}</div>
                  <div className="mt-1 metric text-metric-m text-text-primary">{c.physical_qubits}<span className="ml-1 text-body-s text-text-muted">qubits</span></div>
                  {best && (
                    <div className="mt-1 text-caption text-text-muted">
                      {best.logical_errors === 0 ? (
                        <>
                          0 failures / {best.shots.toLocaleString()} shots
                          <br />
                          95% upper bound {(best.lerpr_ci_high ?? best.ler_ci_high).toExponential(1)}
                        </>
                      ) : (
                        <>best logical err/round {best.logical_error_rate_per_round.toExponential(1)}</>
                      )}
                    </div>
                  )}
                </Card>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}
